version: 2

sources: 
  - name: raw
    schema: main
    tables:
      - name: letterboxd_ratings
        meta:
          external_location: "data/raw/letterboxd/ratings.csv"
        columns:
          - name: Rating
            data_tests:
              - not_null
      - name: movielens_movies
        meta:
          external_location: "data/raw/movielens/movies.csv"
        columns:
          - name: movieId
            data_tests:
              - not_null
              - unique
      - name: movielens_ratings
        meta:
          external_location: "data/raw/movielens/ratings.csv"
        columns:
          - name: userId
            data_tests:
              - not_null
          - name: movieId
            data_tests:
              - not_null

    